### ISSUE TITLE
Add default setting to option in --help output

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/puzzle#101]
For example here:
Options:
  -m, --mode [vcf|gemini]
  -t, --variant-type [snv|sv]  If Structural Variantion or Single Nucleotide
                               variant mode should be used

**Comment by robinandeer** [comment]
Solution is to add `show_default=True` as an option :)

See here: https://github.com/mitsuhiko/click/issues/518#issuecomment-180490926

**Comment by moonso** [comment]
Of course it was there already, it's mitsuhiko!!

**Comment by henrikstranneheim** [comment]
👍

Skickat från min iPhone

**Comment by guillermo-carrasco** [comment]
Awesome, this is good to know, thanks @robinandeer !

**Comment by bittner** [comment]
Would it maybe make sense to make `show_default=True` by default when a `default=` is set? This was also [mentioned on StackOverflow](https://stackoverflow.com/questions/39359420/type-and-default-input-value-of-a-click-option-in-help-option) not too long ago.
