### ISSUE TITLE
VEP REST interface for added/missing info in variant view?

### ISSUE THREAD

**Issue by vasiliosz** [robinandeer/puzzle#108]
http://rest.ensembl.org

<img width="1232" alt="inklistrad_bild_05_02_16_10_33" src="https://cloud.githubusercontent.com/assets/6449441/12842586/02e244ac-cbf4-11e5-8311-5c0cf775155f.png">

**Comment by robinandeer** [comment]
https://pypi.python.org/pypi/pyensemblrest

**Comment by robinandeer** [comment]
What about hacking on this feature together? I think it would give us a chance to think about our code and implement something significant :)

**Comment by robinandeer** [comment]
We've decided that it will add too much complexity for now so we will close this for now, it's more for a hosted tool
