### ISSUE TITLE
Add options for each subcommand

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#113]
Each subcommand should have access to all of its option.

Now:
```
puzzle -t sv view -i vcf
```
Should be:
```
puzzle view -t sv -i vcf
```

**Comment by guillermo-carrasco** [comment]
I personally like having specific options for specific subcommands, and I think its a design choice its this way. I guess its a matter of taste though. Just be sure that the user can't see options that cannot be used by the subcommand she is using. :-)
