### ISSUE TITLE
Utils module refactoring/testing

### ISSUE THREAD

**Issue by guillermo-carrasco** [robinandeer/puzzle#122]
Just though on separating this one to not mix up with the general refactoring referred in #91 

**Testing Utils module TODO list**

- [x] Test `constants.py`
- [x] Test `get_info.py`
    - [x] `get_gene_info`
    - [x] `get_most_severe_consequence`
    - [x] `get_cytoband_coord`
    - [x] `get_omim_number` 
- [x] Test `ped.py`
    - [x]  `get_case`
    - [x] `get_individuals`
- [x] Test `phenomizer.py`
    - [x] `hpo_genes`
- [x] Test `puzzle_database.py`
    - [x] `connect_database`
    - [x] `init_db`

**Comment by moonso** [comment]
Nice Guillermo! I'm so happy you guys have joined :chicken:
