### ISSUE TITLE
Multi-sample gemini database, all variants shown

### ISSUE THREAD

**Issue by Bianca-T** [robinandeer/puzzle#123]
Hi,

I have used puzzle to load a multi-sample (both multiple trios and multiple individual samples).

When I click to look at the variants of a specific family, the variants are not specific for the family but all variants (also from all other samples in the database) are shown.

For example I attach the screenshot of a mutation that I know another sample of my cohort has. Still, it is reported in the variant list of this other family as well.

![screen shot 2016-02-09 at 21 47 54](https://cloud.githubusercontent.com/assets/5881356/12930144/e632ae42-cf76-11e5-89f1-a17721ef1439.png)

Cheers,
Bianca

**Comment by moonso** [comment]
Hello Bianca,

I have a test database with two families but have not experienced this.
We should meet and look at it together, do you have time to come here today?

**Comment by Bianca-T** [comment]
Hi Måns,

When would it work for you? for me best either before lunch or at 14.

/Bianca

**Comment by robinandeer** [comment]
What did you come up with during your meeting? Perhaps add some notes here?

**Comment by moonso** [comment]
Sorry. Yes @Bianca-T noticed that there is a problem with what variants that show up when using the gemini adapter. I'm on this one :rooster:

**Comment by Bianca-T** [comment]
Hi,

I think the problem is still there. For each sample, all variants are loaded, even the one with HOM_REF genotype. This increase the number of variants displayed and therefore the speed of puzzle.

Only HET or HOM_ALT variants should be loaded for each samples (it would be as running "Select * from variants" --gt-filter "gt_types.sampleID == HET or "gt_types.sampleID == HOM_ALT").

/Bianca





![screen shot 2016-03-30 at 14 37 28](https://cloud.githubusercontent.com/assets/5881356/14142269/fc7a2c5e-f684-11e5-8df4-d9c70b0c00cd.png)
