### ISSUE TITLE
How to implement - search and sort functionality for the variants

### ISSUE THREAD

**Issue by guillermo-carrasco** [robinandeer/puzzle#130]
Hi guys, 

Opening this to have an open discussion about the topic, which is:

> We would like to be able to perform queries such as 'show me all high impact variants on chr7:x-y', or 'what variants are heterozyguous in the parents, homozygous in the offspring, and present in this list of genes?' or, in our case 'what variants are present in a set of genomic regions, what is their impact, how often do they occur in our reference set of VCFs?'

[This](https://gemini.readthedocs.org/en/latest/content/querying.html) stuff.

[GQL](https://github.com/genomejs/gql) comes in when you need to query large data sets (especially for genotype queries -- i.e., what percentage of my samples has a G at chr4:1234) which are painfully slow in Gemini (see http://biorxiv.org/content/early/2015/04/20/018259)

So what we're still trying to understand is:

1. Do you have these kind of queries in Puzzle's road map?
2. If so, what workflow do you have in mind for this. Is it VCF/Gemini -> internal DB -> Puzzle ? Then Puzzle will need it's own query system (though we could talk to Aaron to see what could be re-used from Gemini and abstracted away). Or maybe some kind of interface to interact with Gemini/GQL from Puzzle.

Thanks guys! 

Ping @ohofmann @brainstorm :-)

**Comment by moonso** [comment]
Hi,

I will try to answer these questions here. Even though it is hard when we don't know exactly you mean but I will do my best.
In general we reason like this:

- puzzle will have different modes similar to now 
- different modes will have different functionality based on the backend
- the VCF backend will have most limits, the GEMINI backend will be able to do gemini stuff etc.
- we want to design our own backend to be able to do some specific analysies, this is under discussion
- we could create a GQL backend that will have it's limits but will be superfast with huge amount of data(if i understand correct

So for the specific queries above

## show me all high impact variants on chr7:x-y
This is easy to do with the gemini adapter. It is actually easy for the VCF adapter to if we use pytabix. If something is unclear I'll be happy to explain more in detail over a meeting

## what variants are heterozyguous in the parents, homozygous in the offspring, and present in this list of genes?
This is easy with the vcf adapter if the inheritance patterns are annotated with genmod or a similar tool.
Right now it is hard to do with the GEMINI adapter since we can not access the gemini tools from within the python interface. I hope that you guys who already have a contact with the gemini developers can discuss if they can solve this?

## 'what variants are present in a set of genomic regions, what is their impact, how often do they occur in our reference set of VCFs?
This query is a bit vague for me but I defenitely think it is possible. We have to discuss how you want ti use the reference set of VCF:s. If you can merge them in a 1000G kind of way and annotate your vcf:s it will be easy. Otherwise we could implement a wrapper module that query the set of VCF:s for us dynamicly.

I hope this makes sense, and I understand that there are a lot of questions left. Let's continue with the discussion of how to proceed.

**Comment by ohofmann** [comment]
Hey and thanks so much for this! Comments inline:

> I will try to answer these questions here. Even though it is hard when
> we don't know exactly you mean but I will do my best.

Absolutely agree. Let me try and generalize -- I am trying to understand 
how you envision the flow of variant information throughout puzzle. 
Right now you have a mix of VCFs and GeminiDBs which then get processed, 
put into an internal backend, and then exposed to the Puzzle user.

Which means that for any possible analysis or query we can come up with 
you will need to either a) implement the query support yourself 
internally in Puzzle, or b) write a wrapper for Gemini and another for 
the VCFs.

I've been pondering whether it is possible to unify this by going from 
VCF -> Gemini -> Puzzle, with Gemini serving as the query backend. The 
issues I can see with this mostly revolve around flexibility. Right now 
Gemini is _not_ good at just adding a few samples or VCFs to a database, 
you'd have to re-create it from scratch every time. The other issue is 
that I am not sure all the functionality we'd need is exposed through 
the API, although so far we have not stumbled into any problems.

>   * we want to design our own backend to be able to do some specific
>     analysies, this is under discussion

Would love to hear more about this. Ryan Layer and Aaron Quinlan are 
pretty good at listening to community feedback, and I'd be happy to set 
up a call once we have a better idea of what is needed.

> This is easy to do with the gemini adapter. It is actually easy for the
> VCF adapter to if we use pytabix. If something is unclear I'll be happy
> to explain more in detail over a meeting

See above. I was trying to figure out if there's a way to refactor 
things so we do not need two different adapters :)

> Right now it is hard to do with the GEMINI adapter since we can not
> access the gemini tools from within the python interface. I hope that
> you guys who already have a contact with the gemini developers can
> discuss if they can solve this?

Absolutely. Been a while I looked at the Gemini internals (though Rory 
from the Boston team has -- a lot). What access is missing?

> I hope this makes sense, and I understand that there are a lot of
> questions left. Let's continue with the discussion of how to proceed.

Thanks again for the feedback, very much appreciated. Mostly paranoid me 
trying to see what existing resources we can re-use so I don't get 
strangled at the next BOSC meeting.

Best, Oliver



-- 
@fiamh
Skype: ohofmann
+44 795 621 5540

**Comment by moonso** [comment]
Hi,
Sorry about this, it is a bit confusing.

> Which means that for any possible analysis or query we can come up with 
you will need to either a) implement the query support yourself 
internally in Puzzle, or b) write a wrapper for Gemini and another for 
the VCFs.

Right now you can mix gemini and vcfs when loading cases but we will remove this. We have realized that it will be more or less impossible to implement the queries that we want if we allow a VCF and/or GEMINI backend in the same analysis.

So the workflow will be 

VCF->GEMINI (this step is outside the scope of puzzle) -> puzzle
or
VCF->puzzle
or
VCF->puzzle backend->puzzle view

So this will mean that when viewing a database with only VCF: you will have limited choices of analysies.
When viewing a database with gemini backend you can do what gemini does best, and when viewing a database with puzzle backend you can hopefully do even more.

**Comment by moonso** [comment]
> What access is missing?

(From gemini) Right now we would like to be able to use the inheritance tools from within the python interface, but it could be more stuff coming up later. 
Since they have all the logic in place it might not be that difficult for them to implement, or what do you think?

**Comment by ohofmann** [comment]
> remove this. We have realized that it will be more or less impossible to
> implement the queries that we want if we allow a VCF and/or GEMINI
> backend in the same analysis.

That's what I mentioned to Roman and Guillermo a while ago.

> So the workflow will be
>
> VCF->GEMINI (this step is outside the scope of puzzle) -> puzzle
> or
> VCF->puzzle
> or
> VCF->puzzle backend->puzzle view
>
> So this will mean that when viewing a database with only VCF: you will
> have limited choices of analysies.
> When viewing a database with gemini backend you can do what gemini does
> best, and when viewing a database with puzzle backend you can hopefully
> do even more.

Got it now and makes perfect sense. Thanks!

Oliver


-- 
@fiamh
Skype: ohofmann
+44 795 621 5540

**Comment by ohofmann** [comment]
On 12-Feb-16 10:04, Måns Magnusson wrote:
>     What access is missing?
>
> (From gemini) Right now we would like to be able to use the inheritance
> tools from within the python interface, but it could be more stuff
> coming up later.
> Since they have all the logic in place it might not be that difficult
> for them to implement, or what do you think?

Agree, but let me check. More in a bit!

Oliver


-- 
@fiamh
Skype: ohofmann
+44 795 621 5540

**Comment by moonso** [comment]
:+1:

**Comment by brainstorm** [comment]
For the record, so that it doesn't get lost on slack conversations:

"""
I wrote up a quick example here: 
https://gist.github.com/brentp/1f06b43a39c3af67b085 
basically just create the appropriate object, e.g.: 
model = CompoundHet(Args(db="../test/test.comp_het.db", 
columns="chrom,start,end,impact_severity,impact,gene,transcript,max_aaf_all", 
max_priority=3, 
allow_unaffected=True)) 
and then iterate over `model.report_candidates()` which yields OrderedDict's.
"""

I believe @guillermo-carrasco is having a look at it right now, but he might need some further help/examples/testcases.

**Comment by vasiliosz** [comment]
:+1: for pytabix in the VCF adapter. I will have more to say about this in a few days when I've had a chance to test the recent changes, particularly search speed.

**Comment by brentp** [comment]
Let me know if we can help on the gemini end. 

FWIW, [cyvcf2](https://github.com/brentp/cyvcf2), which we use in gemini loading supports doing tabix queries out of the box, so doing a spatial query:

```
vcf = VCF('my.vcf.gz')
for v in vcf('7:123456-2345670'):
     v.start, v.end, v.INFO['DP']
```
is hardly different from just streaming over the vcf:
```
for v in vcf:
   ...
```

the documentation for cyvcf2 is lacking, but the API is pretty simple. so it might be an option for you guys.

**Comment by moonso** [comment]
Thanks @brentp , only problem is to add dependencies of numpy and cython...

**Comment by moonso** [comment]
@vasiliosz I'm not ready with some performance stuff for the vcf adapter. There are som new things that will improve especially SV:s alot coming up

**Comment by vasiliosz** [comment]
@moonso great, I'll wait for those

**Comment by brainstorm** [comment]
@moonso, numpy and cython aren't though to install dependencies when installed with Anaconda or wheels (default on PyPi), IMHO. There's really tons of bioinfo packages using them nowadays, should be considered as "standard" deps for doing performance scientific computing, don't you think?

**Comment by guillermo-carrasco** [comment]
Agree with @brainstorm :-) I lost my fear to these packages when I switched to Anaconda for package and virtual environments management. They're painless to install!

**Comment by moonso** [comment]
Sure, then we should try it!

**Comment by robinandeer** [comment]
@brentp: I'm not as experienced with parsing VCFs as @moonso but will `cyvcf2` parse e.g. the CSQ field or do you have to handle that outside?

**Comment by brentp** [comment]
@robinandeer 
you can get a parsed dict from the info as dict(variant.INFO). and get the keys from that.

I don't think anything will parse the CSQ. In gemini, I just grab the tab-delimited list of keys from the Description field in the vcf header and then the values from each variant info and zip them together.

**Comment by moonso** [comment]
Yes we do it in the same way (with csq)

**Comment by brentp** [comment]
[This](https://github.com/brentp/geneimpacts/) might also be of interest to you guys.

**Comment by moonso** [comment]
@brentp could you add some documentation to cyvcf2 on how to access headers and how to get variants in a region? We should defenitely use this but it is a bit hard to get into right now :smile: 
Some quick questions:
- Are there any restrictions on the vcf file? 
- Does it check each value to what is specified in the header? 
- Does the file need to be ordered on position? 
- Do you need any index?
Thanks!

**Comment by moonso** [comment]
@brentp , I could get some of the answers by looking at the tests :+1:

**Comment by brentp** [comment]
yeah, it definitely needs more docs. but as you found the tests are fairly comprehensive.

> Are there any restrictions on the vcf file?

it has to be parse-able by htslib

> Does it check each value to what is specified in the header?

yes, well htslib does

> Does the file need to be ordered on position?
> Do you need any index?
only if you want to do regional queries

**Comment by moonso** [comment]
Ok, I noticed it does not care about so many things which is good for us!
I will give it a try.

**Comment by moonso** [comment]
Hello all, I'll close this issue for now since most of the stuff is solved.
If there are other requests we can post (smaller) new issues.
It is possible to do range queries, search for high impact variants etc.
