### ISSUE TITLE
Gemini adapter Refractoring/Testing

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#133]
- [x] Test initializing with and without a db
- [x] Test test_gemini_db
- [x] Test case_mixin
    - [x] Test _get_individuals
    - [x] Test _get_cases
    - [x] Test individuals
    - [x] Test case
    - [x] Test cases
- [x] Test varant_mixin
    - [x] Test variant
    - [x] Test variants
    - [x] Test _get_genotypes
    - [x] Test _get_transcripts
    - [x] Test _variants
    - [x] Test _format_variant
    - [x] Test _is_variant

**Comment by guillermo-carrasco** [comment]
Awesome! Can this be closed then?

**Comment by moonso** [comment]
When merged I guess

**Comment by guillermo-carrasco** [comment]
Nice :-D
