### ISSUE TITLE
Create a VCF with sv:s for testing

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#139]
Use same VCF as in #138

**Comment by moonso** [comment]
How about this @vasiliosz , can you do it?

**Comment by vasiliosz** [comment]
Yes, but earliest Fri next week.

**Comment by Bianca-T** [comment]
Can I help you with this? What would you like to have?

**Comment by moonso** [comment]
A VCF with structural variants that is nonsensitive so we can put it on github

**Comment by vasiliosz** [comment]
See discussion in #141. Should use 1kg phase 3 data (for example: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502//ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz)
