### ISSUE TITLE
Implement Apache Spark+ADAM backend

### ISSUE THREAD

**Issue by heuermh** [robinandeer/puzzle#142]
Wanted to drop this in to gauge interest -- we're looking for a front end for variant data stored in [ADAM format](https://github.com/bigdatagenomics/adam) and made available through [Apache Spark](http://spark.apache.org/).

**Comment by moonso** [comment]
Hi! We have no experience with ADAM but if you can see how we could modify puzzle to show the data we are interested. 
Do you have any example on what you want to display?

**Comment by moonso** [comment]
Ok @heuermh , I think we will close this for now.
If there any more interest or ideas how this should be done you can just reopen.
