### ISSUE TITLE
Possibility to VIEW multiple VCFs/GEMINI DBs at once

### ISSUE THREAD

**Issue by guillermo-carrasco** [robinandeer/puzzle#156]
Instead of having to load them one by one?

**Comment by moonso** [comment]
You could do it with a bash for loop like
```
for GEMINI_DB in repo/*.db
do
puzzle load $GEMINI_DB
done
```

**Comment by guillermo-carrasco** [comment]
Ok VCF's can be loaded at once as well, just that if they're compressed then you need to specify a different pattern with `-p *.vcf.gz`.

**Comment by moonso** [comment]
Could we close this one @guillermo-carrasco

**Comment by guillermo-carrasco** [comment]
but one still can't load several GEMINI dbs at once, right?

**Comment by moonso** [comment]
No and it does not really make sense to do so I guess...
The idea with gemini is to collect samples in one database?

**Comment by moonso** [comment]
Why not do a bash-loop like proposed if you really want to do it?

**Comment by guillermo-carrasco** [comment]
yeah ok, or we can merge the DBs outside puzzle. 

Thanks!

**Comment by moonso** [comment]
:tanabata_tree:
