### ISSUE TITLE
Interesting edge case in OMIM

### ISSUE THREAD

**Issue by robinandeer** [robinandeer/puzzle#16]
Was writing tests when I came across this one... I think you understand the molecular stuff better than me!

This is the original gene:
http://www.omim.org/entry/616171?search=MCCRP2&highlight=mccrp2

Which in the JSON is linked to:
http://www.omim.org/entry/605031

But that is another gene PLK4 :/

**Comment by moonso** [comment]
What you say is the original gene is not a gene but a phenotype...

**Comment by robinandeer** [comment]
I really have no idea what is means biologically :P
