### ISSUE TITLE
Use cyvcf2 to parse VCF:s

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#172]
When there is a bgzipped vcf we should use cython for parsing, but still allow unzipped vcf files.

**Comment by moonso** [comment]
Ok to use cyvcf we need to rewrite some parts of the VCF adapter but it is not to much.
The thing that concerns me is that we have to use bgzipped files, if we decide to use cyvcf I think we should skip the old way of doing it otherwise there will be to much code to maintain.
So what do you think @robinandeer , @guillermo-carrasco , @brainstorm , @henrikstranneheim , @dnil , @vasiliosz , is it reasonable to require zipped files?

**Comment by brainstorm** [comment]
IMHO, if the changes are minimal, I think it is worth it:

1. Just a bgzip away from using a faster VCF reader (optimized with cython), also saving up disk space by requiring compression (useful when scaling up analysis, i.e ICGC/TCGA datasets or similar).
2. Avoid regression patches and maintenance such as the one that [popped up a few days ago](https://github.com/moonso/vcftoolbox/pull/5). Using community maintained software.

But perhaps I'm missing important bits @moonso... what are the ups/benefits in doing it the "old way of doing" you mentioned?

**Comment by dnil** [comment]
Fast seems prettier than overly general. Keeping files bgzipped must be better practice.
But, general is good for acceptance. Perhaps attempt to bgzip & index if fed a plain vcf?

**Comment by dnil** [comment]
Guess we don't want pytabix again for now. Do you have experience with e.g. [Bio.bgzf] (http://biopython.org/DIST/docs/api/Bio.bgzf-module.html)? No idea about the speed, but it would be a one-off per file.

**Comment by moonso** [comment]
@brainstorm I'm not sure if we will gain alot of speed, it is rather to use a correct vcf parser. But I agree with your second point.
The benefits of doing the old way is that we have full control when new things pop up, such as when we alowed vcf files that is called by Manta. 
If we use a VCF-parser that is community based it could take longer time to get it to adapt to softare specific formats. But it is nice if we can contribute when things like that comes up :smile:

**Comment by vasiliosz** [comment]
I bgzip my VCFs anyway. Generally, there is no reason why all genomic/variant data files shouldn't be zipped and indexed (even FASTQ files, for parallell alignment). So I say use whatever tools/formats is fastest internally. In Gemini they do what Daniel suggested, bgzip on load - but using the command-line version - altough there the load process is quite slow anyway, so its not an obvious delay. Because yes, it will take a long time to decompress and rezip with bgzip at first load. So I would probably prefer a warning with example code for the user to run it themselves. 

Potential drawbacks: puzzle will not be able to handle "any" VCF-file anymore, and introduces a barrier to use that may prove too much for some users.

**Comment by moonso** [comment]
@dnil yes I have also thought about that, see https://github.com/brentp/cyvcf2/issues/7, if that would work there is no problems, then we will just try to compress it before loading/viewing.
I have no experience with Bio.bgzf...

**Comment by moonso** [comment]
@vasiliosz agree. But in the end I think bgzipped files if a small requirement compared to the benefits.

**Comment by dnil** [comment]
Make a small test with cyvcf and a range of sv variants to make sure it is handling them ok first?

**Comment by moonso** [comment]
I'm on it @dnil !

**Comment by moonso** [comment]
I misunderstod, we can use cyvcf2 without zipped files so it is straight forward :rocket:
