### ISSUE TITLE
Guess mode and variant type

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#178]
We should let puzzle find out if it is looking at a gemini db or a vcf and if it is sv:s or snv:s

**Comment by moonso** [comment]
When `puzzle` is used to look at files or a directory of files it should create a in memory sqlite database so that the interface will be identical to when it is viewing a puzzle database

**Comment by robinandeer** [comment]
If we want to use some kinds of notifications, I like how thes ones look:

https://sciactive.github.io/pnotify/

**Comment by moonso** [comment]
If it is lying there all the time I would go crazy..

**Comment by robinandeer** [comment]
no, it would fade out after a set amount of seconds :zap:

**Comment by moonso** [comment]
:+1:

**Comment by moonso** [comment]
Closed by #186
