### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/puzzle#180]
Currently there is a mix of swedish and english in the webb interface. For instance: “Bläddra Ingen fil vald”

Let's stick to english, :)

**Comment by robinandeer** [comment]
I agree it might look weird, but in that case it's the browser that decides based on which language settings the computer has - on my computer is show up as "Choose file - no file chosen" :/

**Comment by moonso** [comment]
But if the browser chooses there should be no problem for the user right??

**Comment by henrikstranneheim** [comment]
No, then it should be fine. 


> On 10 Mar 2016, at 16:43, Måns Magnusson <notifications@github.com> wrote:
> 
> But if the browser chooses there should be no problem for the user right??
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/robinandeer/puzzle/issues/180#issuecomment-194913527>.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se <mailto:henstr18@kth.se>
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
