### ISSUE TITLE
Frequency filter stopped working?

### ISSUE THREAD

**Issue by dnil** [robinandeer/puzzle#217]
Tested w/ Safari, VEP annotation, vcf-file, init,load&view.

**Comment by moonso** [comment]
What happens?

**Comment by dnil** [comment]
Absolutely nothing. Variants are displayed unfiltered.

**Comment by dnil** [comment]
Where do you set max_freq now? Used to be part of the vcf-adapter variant_extras right?

**Comment by moonso** [comment]
https://github.com/robinandeer/puzzle/blob/master/puzzle/plugins/vcf/mixins/variant_mixin.py#L316

**Comment by dnil** [comment]
Thanks; just rediscovered the model part...

**Comment by dnil** [comment]
Ah, just a missing call to _add_exac...

**Comment by moonso** [comment]
This was fixed by your PR, right @dnil ?

**Comment by dnil** [comment]
Right!
