### ISSUE TITLE
Dynamic Filters?

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#27]
Is it possible to open different filters depending on what frequencies that are used?

**Comment by robinandeer** [comment]
We would solve this by only focusing on a global frequency filter, right?

**Comment by moonso** [comment]
That one is decided but I mean that the gemini-adapter for example might have different functionality than the vcf adapter etc...

**Comment by moonso** [comment]
Let's close this until we get some ideas of how to do it
