### ISSUE TITLE
Filter on genetic models

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#33]
- [x] Interface
- [ ] Backend

**Comment by robinandeer** [comment]
I've added a filter in the interface :)

**Comment by moonso** [comment]
Nice I'll have a look soon!

**Comment by moonso** [comment]
What terms do you use for the different models?

**Comment by robinandeer** [comment]
Short versions like in Scout: AR, AR_hom etc.

**Comment by moonso** [comment]
Ok so how should we send this and functional filter to adapter? Is it with a list?

**Comment by robinandeer** [comment]
Yes :+1:
