### ISSUE TITLE
Help needed running puzzle tests

### ISSUE THREAD

**Issue by Bianca-T** [robinandeer/puzzle#40]
Hi,

I wanted to have a look at puzzle but got the following error:
![screen shot 2015-10-22 at 14 33 16](https://cloud.githubusercontent.com/assets/5881356/10665231/00cfb32a-78ca-11e5-9100-33f914020c35.png)

Puzzle is correctly installed.

Can you help me?

Thanks,
Bianca

**Comment by moonso** [comment]
Hi Bianca, glad you are testing!

The documentation is not really up to date, if you run ```puzzle --help``` you will see:

```
Usage: puzzle [OPTIONS] ROOT COMMAND [ARGS]...

  Puzzle: manage DNA variant resources.

Options:
  -p, --plugin [vcf|gemini]
  -v, --verbose
  --help                     Show this message and exit.

Commands:
  view  Visualize DNA variant resources.
```

so you need to use the command ```view``` to test it.
If you want to run on the test data do 
```
puzzle tests/ view
```

Or you can point on another directory with your own files.

If you want to try with a gemini database do
```
puzzle --plugin gemini path/to/database.db view
```

Good luck!

**Comment by Bianca-T** [comment]
:+1:
