### ISSUE TITLE
Mark affected cases with color in genotype table on variant view

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#44]
A ```Case``` will have ```self['individuals']```and a ```Individual``` will have ```individual['phenotype']```.
Just do:

```python
if individual.get('phenotype',0) == 2:
    #mark red
```

**Comment by robinandeer** [comment]
I use `individual.affected` but it's the same I guess

**Comment by moonso** [comment]
sure

**Comment by robinandeer** [comment]
I've highlighted the affected samples, can be improved in the future tho
