### ISSUE TITLE
Add SV analysis mode

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#61]
We should allow the user to specify SV analysis mode.
When in this mode the overview and variant page will look a bit different since the variants are completely different.

**Comment by moonso** [comment]
## SV overview:

- [ ] sv-type
- [ ] Limit the viewing of number of genes overlapped(for large svs)
- [ ] Column with number of genes overlapped
- [ ] Column with size
- [ ] Remove consequence, 1000G, CADD

**Comment by moonso** [comment]
## SV variant view

- Sv-type
- pos
- end
- Switch transcript table to gene table ```|Gene id|Location|Description|Omim|Morbid|DDGP2|HapploInsufficiency(HI) score|```

**Comment by moonso** [comment]
##Filters 

- types
- size
- inter/intrachromosomal
- Ovelapping genes(nr of genes overlapped)

**Comment by vasiliosz** [comment]
Haploinsufficiency scores are here as `Table S1`: http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1001154#s5
Functional gene constraint (from ExaC) here: ftp://ftp.broadinstitute.org/pub/ExAC_release//release0.3/functional_gene_constraint/forweb_cleaned_exac_r03_march16_z_data_pLI.txt

**Comment by moonso** [comment]
:+1:
