### ISSUE TITLE
Incomplete HGNC to EnsemblID 

### ISSUE THREAD

**Issue by vasiliosz** [robinandeer/puzzle#69]
There are lots of gene symbols that do not get a matching Ensembl ID (that should) in the variant view. 

Are they collected from `resources/hgnc_to_omim.json`? Is it only OMIM genes that then get EnsemblIDs also?

**Comment by moonso** [comment]
Yes there are only omit genes there.
We are working on another package that will include all the details that we want.

**Comment by moonso** [comment]
Waiting for recourses from @ingkebil

**Comment by moonso** [comment]
Fixed now since we use [phizz](https://github.com/moonso/phizz)
