### ISSUE TITLE
Add individuals to index page

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#74]
We should have a link to apage that shows all individuals found in the database

**Comment by robinandeer** [comment]
Yep, and this is where you would select a custom "case"

But it could probably fit on the same page as cases, perhaps using tabs?

**Comment by robinandeer** [comment]
I can do this too in the next server update

**Comment by moonso** [comment]
Super, we should also think of how we can add different ways of filter the individuals. We could start with HPO. So 'give me all individuals with HPO term x'.
