### ISSUE TITLE
How to use Puzzle?

### ISSUE THREAD

**Issue by Bianca-T** [robinandeer/puzzle#83]
Hi,

I updated to the newest version of puzzle, and I can't find outhow to load a VCF in SV mode.
Can you update the usage examples?

Thanks,
Bianca

**Comment by vasiliosz** [comment]
The `-t` option seems to be bound twice now, to snv/sv and "family type": 

https://github.com/robinandeer/puzzle/blob/master/puzzle/cli.py#L28-L32
and
https://github.com/robinandeer/puzzle/blob/master/puzzle/cli.py#L104-L107

Previously the option was `-m sv` I think

**Comment by moonso** [comment]
Yes it is hard to make up unique one-letter flags...
The interface is a bit different now since the last update, please try `puzzle init` and `puzzle load`!
The command for viewing a vcf file with sv variants is now:
```puzzle -t sv view -i path/to/file.vcf```

**Comment by moonso** [comment]
Sorry about that, we will have a more stable version of puzzle with documentation within a few weeks...

**Comment by vasiliosz** [comment]
Great! 

`puzzle init`
`puzzle load`
`puzzle delete -f myfam1`

..all work nicely. 

However, it defaults to loading them in `snv` mode. And the `-t` flag is already busy in the `puzzle load` cmd as mentioned. Running `puzzle -t sv view` after that doesn't matter it seems - still shows snv mode

```
[130-229-10-171-dhcp puzzle]$ puzzle load -i /path/to/myfam1.merged.snpeff.vcf.gz -f /path/to/myfam1.ped 
[2016-02-01 19:06:27,132] puzzle.cli                INFO     Root directory is: /path/to/.puzzle
[2016-02-01 19:06:27,133] puzzle.cli                INFO     Initialzing VCF plugin
[2016-02-01 19:06:27,133] puzzle.plugins.vcf.vcf    INFO     Updating root path to /path/to/myfam1.merged.snpeff.vcf.gz
[2016-02-01 19:06:27,133] puzzle.plugins.vcf.vcf    INFO     Setting variant type to snv
```

**Comment by moonso** [comment]
The idea is to specifythat when loading, it should look like:
```puzzle -t sv load -i ... -f ...```

Then just `puzzle view`

**Comment by vasiliosz** [comment]
Thanks, I didn't realize the `-t` option had to go before load. Now it works

**Comment by moonso** [comment]
:+1:

**Comment by Bianca-T** [comment]
Thanks it works!!
