### ISSUE TITLE
Filters are slow with vcf adapter

### ISSUE THREAD

**Issue by moonso** [robinandeer/puzzle#85]
Some filters are way to slow with vcf adapter, this probably have to do with that we build the whole variant object before we start to do the filtering.

**Comment by vasiliosz** [comment]
+1

A gene search in a two-sample SV VCF (~6000 vars) took 10 min.
In a 12-sample VCF with >1M vars it didn't finish in at least 30min. 

I understand you plan to load them into the db(?), but would a "grep-like" approach work in cases where just a VCF is provided? (And the build the object based on the returned lines)

Alternatively, if the VCF is tabixed you could convert the gene to coordinates (with a lookup) and then pull the region. Should be faster.

**Comment by vasiliosz** [comment]
Too slow :)

**Comment by moonso** [comment]
Have you tried the new update? Still that slow?

**Comment by moonso** [comment]
I have a file from you with 6000 variants where a gene search only takes a couple of seconds...

**Comment by vasiliosz** [comment]
Will try!

Skickat från min iPhone

**Comment by vasiliosz** [comment]
Takes ~20-25s for one gene in a VCF with >1M variants now  (MBP15" i7). Much better @moonso!

**Comment by moonso** [comment]
:+1:  is that ok for you?

**Comment by vasiliosz** [comment]
Its workable I think.

However, if I load more variants (after the top 31) - it will actually redo the search. So it will be painful to wait up to 30s per page load if you scroll through many of them. I guess it's related to the discussion in #90

**Comment by robinandeer** [comment]
After "load more" we should skip ahead in the loop - can you do this in the adapter before your optimizations, @moonso?
