### ISSUE TITLE
More robust way to locating "resources"

### ISSUE THREAD

**Issue by robinandeer** [robinandeer/puzzle#89]
It doesn't seem to start puzzle from any location at the moment, no?

It tries and fails to find "resources" files I've noticed

**Comment by moonso** [comment]
Ok let's read up on this and fix it

**Comment by moonso** [comment]
Do we have any suggestions/examples on how to solve this one?

**Comment by robinandeer** [comment]
yup, I have code in Chanjo that handles this:
https://github.com/robinandeer/chanjo/blob/master/chanjo/demo/cli.py

Also see `setup.py`

**Comment by robinandeer** [comment]
Maybe for todays coding session?

**Comment by moonso** [comment]
Agree, it is a perfect thing for today!
