### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by robinandeer** [robinandeer/puzzle#91]
This is an effort to go over the code base and re-think some of the structure in a future proof way. We will also focus on test coverage for smaller subunits at the same time.

**Topics**
- [x] Server code/Flask @robinandeer
- [x] Models @moonso
- [x] GEMINI adapter @moonso 
- [x] VCF adapter @moonso 
- [x] SQL adapter @robinandeer
- [x] Utils @moonso 
- [x] CLI + logging @moonso 

Feel free to assign yourself or suggest a new topic!

**Comment by guillermo-carrasco** [comment]
If you're planning to do some kind of intense one-day kick-off hackathon, I'd love to attend :-)

**Comment by robinandeer** [comment]
I'm not complaining :dancer:

**Comment by robinandeer** [comment]
Flask structure, some inspiration:

- [ ] https://github.com/masom/bluemonk/blob/master/bluemonk/views/helpdesk.py
- [ ] https://github.com/mattupstate/overholt
- [ ] https://github.com/mbr/flask-bootstrap/tree/master/sample_app :+1: 
- [ ] https://github.com/mbr/flask-debug
- [ ] https://pythonhosted.org/Flask-Bootstrap/nav.html

**Comment by guillermo-carrasco** [comment]
Testing: I’ve noticed that you guys have created a file per function to test, at least in the utils module. That makes it difficult to know which functions are being tested in which submodules. Is that a pytest common practice? I would propose a file per module to test, within the file, a class per submodule. i.e for the utils module: `tests/utils/test_utils.py` (a bit redundant, could be `tests/tests_utils.py`):

```python
class TestGetInfo():
    ”””All tests for the methods in get_info.py”””
   …

class TestPhenomizer():
    ”””All tests for the methods in phenomizer.py”””
```

**Comment by guillermo-carrasco** [comment]
More concrete example: https://github.com/guillermo-carrasco/puzzle/commit/c6dcbdab89e2dcd6797c8dbcc2b4613ab831d602

**Comment by moonso** [comment]
Looks great!

**Comment by moonso** [comment]
Refractor of CLI in #128
