### ISSUE TITLE
HPO term does not load

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/puzzle#95]
It would be nice to get feeedback if the HPO term does not exist in the Phizz db.

**Comment by moonso** [comment]
We can try to add this

**Comment by robinandeer** [comment]
I guess this is something for the server, no? I'll take lead on this

**Comment by moonso** [comment]
Yes server thing

**Comment by guillermo-carrasco** [comment]
What kind of feedback were you thinking about? Log message/pop up/something in the interface?

**Comment by robinandeer** [comment]
There is a very nice feature in Flask called `flash` which is kinda for these things - would you like to add that functionality @guillermo-carrasco?

It will likely be some kind of list on the base layout

http://flask.pocoo.org/docs/0.10/patterns/flashing/

**Comment by guillermo-carrasco** [comment]
Sure, I would need a bit more `-v` though. Like a use case scenario, you know what I mean?

**Comment by robinandeer** [comment]
You are such a geek :sweat_smile: 

Luckily I read you, hehe

When the error is detected on the server it should be handled gracefully and log a message using the `flash` function. The message should then show up during the next page load (taken care of by Flask) as a notice (maybe a popup in the top right corner?) should inform the user :)

```python
try:
    fun()
except:
    flash("HPO term ({}) not found in database".format(term))
    return redirect(request.referer)
```

**Comment by guillermo-carrasco** [comment]
ah, nice :-) :eyeglasses: tack @robinandeer

**Comment by robinandeer** [comment]
Any time, hacker :hamburger: 
I look forward to reviewing your code

**Comment by moonso** [comment]
Was this fixed @guillermo-carrasco , @robinandeer ?

**Comment by guillermo-carrasco** [comment]
Hmm nope, I'll do it now.

**Comment by moonso** [comment]
:+1:
