### ISSUE TITLE
Compounds should be sorted on score in descending order

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/puzzle#96]

**Comment by moonso** [comment]
Should be done in the interface, right @robinandeer ?

**Comment by robinandeer** [comment]
depends on where the logic is easiest to test and maintain but I'll look into it, shouldn't be to difficult (until we want to show them as popups as in Scout at least)

**Comment by robinandeer** [comment]
Could perhaps be in the model as well

**Comment by moonso** [comment]
Sure I can do this in the model

**Comment by robinandeer** [comment]
Have you looked into this already @moonso? I guess the server will just continue as usual and not have to change anything, right?

**Comment by moonso** [comment]
I agree but haven't looked at it yet.

**Comment by henrikstranneheim** [comment]
Compounds are now sorted in ascending order. Would be nice to have them in descending order i.e. 40, 30, 20 etc, so that the most important one are presented first and not last
