### ISSUE TITLE
Sometimes a the HGNC_symbol is missing from the overview

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/puzzle#98]
![screen shot 2016-02-04 at 10 03 23](https://cloud.githubusercontent.com/assets/584738/12810469/be338d7a-cb26-11e5-90f9-1a19682094c4.png)
![screen shot 2016-02-04 at 10 04 15](https://cloud.githubusercontent.com/assets/584738/12810478/c5e65098-cb26-11e5-9b6b-9e0e28a8b1fb.png)

But exists in the variant entry

**Comment by moonso** [comment]
Ok that looks wierd, I'll have a look
